"""Generate parametric OpenSCAD scripts from DrawingData."""

from __future__ import annotations
import os
from data_model import DrawingData, Dimension, Shape


def generate_scad(data: DrawingData, output_path: str) -> None:
    """Write a parametric .scad file from extracted drawing data."""
    lines = _build_scad(data)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def _build_scad(data: DrawingData) -> list[str]:
    lines: list[str] = []

    # Header
    lines += [
        f"// Auto-generated by extract-dimensions",
        f"// Source: {data.source}  |  Method: {data.extraction_method}  |  Units: {data.units}",
        "",
    ]

    # Parameters section
    lines.append("// === Parameters ===")
    param_names: dict[str, str] = {}  # label → scad variable name
    for dim in data.dimensions:
        var = _safe_var(dim.label)
        # Avoid collisions
        suffix = ""
        candidate = var
        used = set(param_names.values())
        n = 1
        while candidate + suffix in used:
            n += 1
            suffix = f"_{n}"
        var = candidate + suffix
        param_names[dim.label] = var
        tol_comment = f"  // {dim.tolerance}" if dim.tolerance else ""
        lines.append(f"{var} = {dim.value};  // {dim.unit}{tol_comment}")

    if data.extrude_height is not None:
        lines.append(f"extrude_h = {data.extrude_height};  // {data.units}")
    lines.append("")

    # 2D profile module
    lines.append("// === 2D Profile ===")
    lines.append("module profile_2d() {")

    solids, holes = _classify_shapes(data.shapes)

    if holes:
        lines.append("    difference() {")
        indent = "        "
        for shape in solids:
            lines += [f"    {l}" for l in _render_shape(shape, indent="    ")]
        for shape in holes:
            lines += [f"    {l}" for l in _render_shape(shape, indent="    ")]
        lines.append("    }")
    elif solids:
        for shape in solids:
            lines += [f"    {l}" for l in _render_shape(shape, indent="")]
    else:
        lines.append("    // No shapes extracted — add your geometry here")
        lines.append("    square([10, 10]);")

    lines.append("}")
    lines.append("")

    # 3D model or 2D export
    lines.append("// === Output ===")
    if data.extrude_height is not None:
        lines += [
            "linear_extrude(height = extrude_h) {",
            "    profile_2d();",
            "}",
        ]
    else:
        lines += [
            "// No extrusion height provided — rendering 2D profile",
            "profile_2d();",
        ]

    return lines


def _classify_shapes(shapes: list[Shape]) -> tuple[list[Shape], list[Shape]]:
    """
    Heuristic: small circles nested inside larger polygons/rectangles are holes.
    Everything else is a solid.
    """
    if len(shapes) <= 1:
        return shapes, []

    # Find bounding box of largest shape to determine what's "inside"
    solids: list[Shape] = []
    holes: list[Shape] = []

    # Gather all circle shapes — treat small circles as holes if there's a larger solid
    non_circles = [s for s in shapes if s.type not in ("circle", "arc")]
    circles = [s for s in shapes if s.type in ("circle", "arc")]

    if non_circles and circles:
        solids = non_circles
        holes = circles
    else:
        solids = shapes

    return solids, holes


def _render_shape(shape: Shape, indent: str = "") -> list[str]:
    """Render a single Shape to OpenSCAD lines."""
    lines: list[str] = []
    if shape.type == "rectangle":
        x = shape.x or 0.0
        y = shape.y or 0.0
        w = shape.width or 10.0
        h = shape.height or 10.0
        if x == 0 and y == 0:
            lines.append(f"{indent}square([{_f(w)}, {_f(h)}]);")
        else:
            lines.append(f"{indent}translate([{_f(x)}, {_f(y)}])")
            lines.append(f"{indent}    square([{_f(w)}, {_f(h)}]);")

    elif shape.type in ("circle", "arc"):
        cx, cy = (shape.center or [0.0, 0.0])
        r = shape.radius or 5.0
        if cx == 0 and cy == 0:
            lines.append(f"{indent}circle(r = {_f(r)});")
        else:
            lines.append(f"{indent}translate([{_f(cx)}, {_f(cy)}])")
            lines.append(f"{indent}    circle(r = {_f(r)});")

    elif shape.type == "polygon":
        if shape.points:
            pts = ", ".join(f"[{_f(p[0])}, {_f(p[1])}]" for p in shape.points)
            lines.append(f"{indent}polygon(points = [{pts}]);")
        else:
            lines.append(f"{indent}// Empty polygon")

    else:
        lines.append(f"{indent}// Unknown shape type: {shape.type}")

    return lines


def _safe_var(label: str) -> str:
    """Convert a label string to a safe OpenSCAD variable name."""
    import re
    name = re.sub(r"[^a-zA-Z0-9_]", "_", label.lower())
    if name and name[0].isdigit():
        name = "v_" + name
    return name or "dim"


def _f(value: float) -> str:
    """Format a float, removing trailing zeros."""
    return f"{value:.4f}".rstrip("0").rstrip(".")
